# Generated by Django 5.0.4 on 2024-05-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='upcomingprojects',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
