# Generated by Django 5.0.4 on 2024-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
