# Generated by Django 5.0.4 on 2024-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_enquiry_options_alter_enquiry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='upcomingprojects',
            name='description',
            field=models.TextField(),
        ),
    ]
