# Generated by Django 5.0.4 on 2024-05-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_image_alter_upcomingprojects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='upcomingprojects',
            name='image',
        ),
        migrations.AddField(
            model_name='upcomingprojects',
            name='image',
            field=models.ManyToManyField(to='app.image'),
        ),
    ]
