# Generated by Django 5.0.4 on 2024-05-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_image_remove_upcomingprojects_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='AppImage',
        ),
    ]
