# Generated by Django 5.0.4 on 2024-05-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_image_appimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appimage',
            old_name='description',
            new_name='alt',
        ),
    ]
