# Generated by Django 5.0.4 on 2024-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_description_appimage_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ManyToManyField(to='app.appimage'),
        ),
    ]
