# Generated by Django 5.0.4 on 2024-06-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_project_image_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatePartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='associate_partners/')),
            ],
        ),
    ]
