# Generated by Django 5.0.4 on 2024-06-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
